baseURL = 'https://LainKanti.github.io/'
languageCode = 'en-us'
title = 'LainKanti'
theme = 'risotto'

[caches]
	[caches.images]
	dir = ':cacheDir/images'

[params]
author = "baz"
description = "A hugo site powered by risotto"
favicon = "favicon.ico"

[menu]
	[[menu.main]]
	identifier = "about"
	name = "about"
	url = "/about/"
	weight = 1

	[[menu.main]]
	identifier = "posts"
	name = "posts"
	url = "/posts/"
	weight = 2
